-- run_test.py: invoking following command in '/home/student/ros2_ws/src/TrailBotPro':
 - /opt/ros/humble/bin/ament_xmllint --xunit-file /home/student/ros2_ws/src/TrailBotPro/build/test_results/41068_ignition_bringup/xmllint.xunit.xml

Traceback (most recent call last):
  File "/opt/ros/humble/bin/ament_xmllint", line 33, in <module>
    sys.exit(load_entry_point('ament-xmllint==0.12.14', 'console_scripts', 'ament_xmllint')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ament_xmllint/main.py", line 78, in main
    parser.parse(filename)
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python3.10/xml/sax/saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/home/student/ros2_ws/src/TrailBotPro/install/41068_ignition_bringup/share/41068_ignition_bringup/package.xml'


-- run_test.py: return code 1
-- run_test.py: generate result file '/home/student/ros2_ws/src/TrailBotPro/build/test_results/41068_ignition_bringup/xmllint.xunit.xml' with failed test
-- run_test.py: verify result file '/home/student/ros2_ws/src/TrailBotPro/build/test_results/41068_ignition_bringup/xmllint.xunit.xml'
