-- run_test.py: invoking following command in '/home/student/ros2_ws/src/TrailBotPro':
 - /opt/ros/humble/bin/ament_pep257 --xunit-file /home/student/ros2_ws/src/TrailBotPro/build/test_results/41068_ignition_bringup/pep257.xunit.xml

Error in file ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition.launch.py'
Error in file ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition_drone.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition_drone.launch.py'
Error in file ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_navigation.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_navigation.launch.py'
checking ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition.launch.py
./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition.launch.py'
checking ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition_drone.launch.py
./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition_drone.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_ignition_drone.launch.py'
checking ./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_navigation.launch.py
./install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_navigation.launch.py: [Errno 2] No such file or directory: './install/41068_ignition_bringup/share/41068_ignition_bringup/launch/41068_navigation.launch.py'
checking ./install/_local_setup_util_ps1.py
checking ./install/_local_setup_util_sh.py
checking ./launch/41068_ignition.launch.py
checking ./launch/41068_ignition_drone.launch.py
checking ./launch/41068_navigation.launch.py
3 errors


-- run_test.py: return code 1
-- run_test.py: verify result file '/home/student/ros2_ws/src/TrailBotPro/build/test_results/41068_ignition_bringup/pep257.xunit.xml'
