<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="41068_ignition_bringup" tests="1" failures="0" time="1.133" errors="1" skipped="0">
  <testcase classname="41068_ignition_bringup" name="xmllint.xunit.missing_result" time="1.133">
    <error message="The test did not generate a result file:&#10;&#10;Traceback (most recent call last):&#10;  File &quot;/opt/ros/humble/bin/ament_xmllint&quot;, line 33, in &lt;module&gt;&#10;    sys.exit(load_entry_point('ament-xmllint==0.12.14', 'console_scripts', 'ament_xmllint')())&#10;  File &quot;/opt/ros/humble/lib/python3.10/site-packages/ament_xmllint/main.py&quot;, line 78, in main&#10;    parser.parse(filename)&#10;  File &quot;/usr/lib/python3.10/xml/sax/expatreader.py&quot;, line 105, in parse&#10;    source = saxutils.prepare_input_source(source)&#10;  File &quot;/usr/lib/python3.10/xml/sax/saxutils.py&quot;, line 365, in prepare_input_source&#10;    f = urllib.request.urlopen(source.getSystemId())&#10;  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 216, in urlopen&#10;    return opener.open(url, data, timeout)&#10;  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 503, in open&#10;    req = Request(fullurl, data)&#10;  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 322, in __init__&#10;    self.full_url = url&#10;  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 348, in full_url&#10;    self._parse()&#10;  File &quot;/usr/lib/python3.10/urllib/request.py&quot;, line 377, in _parse&#10;    raise ValueError(&quot;unknown url type: %r&quot; % self.full_url)&#10;ValueError: unknown url type: '/home/student/ros2_ws/src/TrailBotPro/install/41068_ignition_bringup/share/41068_ignition_bringup/package.xml'&#10;"/>
  </testcase>
</testsuite>
